[[plugins]]
repo = 'github/copilot.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'MeanderingProgrammer/render-markdown.nvim'
depends = ['copilot.vim', 'plenary.nvim', 'CopilotChat.nvim', 'codecompanion.nvim']
lua_add = '''
require('render-markdown').setup({
  file_types = { 'markdown', 'copilot-chat', 'codecompanion' },
})
'''

[[plugins]]
repo = 'CopilotC-Nvim/CopilotChat.nvim'
depends = ['copilot.vim', 'plenary.nvim']
hooks_file = '$XDG_CONFIG_HOME/nvim/hooks/copilotchat.lua'
