[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = ['ddc.vim', 'vim-lsp']

#-----------------------------------------------------------------------
# ddu settings
#-----------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = '''

"-----------------------------------------------------------------------
" ddu filer settings
"-----------------------------------------------------------------------
nmap <silent> ,m <Cmd>call ddu#start({ 'name' : 'file' })<CR>

" fuzzy find full text search
nmap <silent> ,g <Cmd>call ddu#start({
\   'name': 'text',
\   'sources': [{
\     'name': 'rg',
\     'options': {
\       'matchers': [],
\       'volatile': v:true,
\      },
\   }],
\   'uiParams': {'ff': {
\     'ignoreEmpty': v:false,
\     'autoResize': v:false,
\   }},
\ })<CR>


" fuzzy find buffer
nmap <silent> ,b <Cmd>call ddu#start({ 'name' : 'buffer' })<CR>

" fuzzy find grep cursor word
nmap <silent> ,w <Cmd>call ddu#start({
\   'name': 'word',
\   'sources':[
\     {'name': 'rg', 'params': { 'input': expand('<cword>')}}
\   ],
\ })<CR>

" ddu Global Setting
call ddu#custom#patch_global({
\   'ui': 'ff',
\   'sourceOptions': {
\     '_': {
\       'matchers': ['matcher_substring'],
\     },
\     'file': {
\       'columns': ['icon_filename'],
\     },
\   },
\   'kindOptions': {
\     'file': {
\       'defaultAction': 'open',
\     },
\   },
\   'uiParams': {
\     'ff': {
\       'prompt': '> ',
\       'split': 'floating',
\     },
\    'filer': {
\       'split': 'floating',
\       'sortTreesFirst': v:true,
\     }
\  },
\ })

"-----------------------------------------------------------------------
" ddu filer settings
"-----------------------------------------------------------------------
call ddu#custom#patch_local('file', {
\   'ui': 'filer',
\   'sources': [{'name': 'file', 'params': {}}]
\ })

autocmd FileType ddu-filer call s:ddu_filer_my_settings()
function! s:ddu_filer_my_settings() abort
  " Change action, Is cursor item drectory or not.
  nnoremap <buffer><silent><expr> <CR>
        \ ddu#ui#get_item()->get('isTree', v:false) ?
        \ "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'narrow'})<CR>" :
        \ "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'open'})<CR>"
  " Move to higher path
  nnoremap <buffer><silent> ..
        \ <Cmd>call ddu#ui#sync_action('itemAction', {'name': 'narrow', 'params': {'path': '..'}})<CR>
  nnoremap <buffer><silent> c
        \ <Cmd>call ddu#ui#sync_action('itemAction', {'name': 'copy'})<CR>
  nnoremap <buffer><silent> d
        \ <Cmd>call ddu#ui#sync_action('itemAction', {'name': 'delete'})<CR>
  nnoremap <buffer><silent> mv
        \ <Cmd>call ddu#ui#sync_action('itemAction', {'name': 'move'})<CR>
  nnoremap <buffer><silent> r
        \ <Cmd>call ddu#ui#sync_action('itemAction', {'name': 'rename'})<CR>
  nnoremap <buffer><silent> t
        \ <Cmd>call ddu#ui#sync_action('itemAction', {'name': 'newFile'})<CR>
  nnoremap <buffer><silent> mk
        \ <Cmd>call ddu#ui#sync_action('itemAction', {'name': 'newDirectory'})<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#sync_action('toggleSelectItem')<CR>
  nnoremap <buffer> o
        \ <Cmd>call ddu#ui#sync_action('expandItem', {'mode': 'toggle'})<CR>
  nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#sync_action('quit')<CR>
endfunction
"-----------------------------------------------------------------------
" end ddu filer settings
"-----------------------------------------------------------------------

" fuzzy find full text search setting
call ddu#custom#patch_local('text', {
\   'sourceParams' : {
\     'rg' : {
\       'args': ['--column', '--no-heading', '--color', 'never', '--sort-files', '--hidden'],
\     },
\   },
\   'uiParams': {
\     'ff': {
\       'startFilter': v:true,
\     }
\   },
\ })

" fuzzy find buffer
call ddu#custom#patch_local('buffer', {
\   'sources': [{'name': 'buffer', 'params': {}}],
\   'sourceParams' : {
\     'rg' : {
\       'args': ['--column', '--no-heading', '--color', 'never'],
\     },
\   },
\   'uiParams': {
\     'ff': {
\       'startFilter': v:true,
\     }
\   },
\ })

" fuzzy find grep cursor word setting
call ddu#custom#patch_local('word', {
\   'sourceParams' : {
\     'rg' : {
\       'args': ['--column', '--no-heading', '--color', 'never'],
\     },
\   },
\   'uiParams': {
\     'ff': {
\       'startFilter': v:true,
\     }
\   },
\ })

" from ddu document
autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

" from ddu document
autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
  nnoremap <buffer><silent> q
  \ <Cmd>close<CR>
endfunction
'''

# filer
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'

# filer
[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

# icon
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'

# filer
[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

#-----------------------------------------------------------------------
# end of ddu settings
#-----------------------------------------------------------------------

[[plugins]]
repo = 'wakatime/vim-wakatime'
hook_add = '''
if has('nvim') && isdirectory( $PYENV_ROOT.'/versions/neovim3' )
  let g:wakatime_PythonBinary = $PYENV_ROOT.'/versions/neovim3/bin/python'
endif
'''

# vim session save
[[plugins]]
repo = 'tpope/vim-obsession'
hook_add = '''  
  noremap <silent> <S-C-s> :mksession<CR>
'''

# 自動括弧閉じ
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
  "call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': '{', 'input': '{'})
  "call lexima#add_rule({'at': '\%#\n\s*}', 'char': '}', 'input': '}', 'delete': '}'})
'''

# 画面分割機能強化
[[plugins]]
repo = 'simeji/winresizer'

# toml syntax
[[plugins]] 
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'


# フロントエンド周り
[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
  require'colorizer'.setup()
EOF
'''
# フロントエンド周り

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
