[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufEnter'
lua_source = '''
  local nvim_lspconfig = require('lspconfig')
  local opts = { noremap=true, silent=true }
  vim.keymap.set('n', 'ge', vim.diagnostic.open_float)
  vim.keymap.set('n', 'g[', vim.diagnostic.goto_prev)
  vim.keymap.set('n', 'g]', vim.diagnostic.goto_next)
  vim.api.nvim_create_autocmd('LspAttach', {
    local bufopts = { noremap=true, silent=true, buffer=bufnr }
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
  })
  vim.lsp.set_log_level("debug")
  nvim_lspconfig.rust_analyzer.setup {
    -- Server-specific settings. See `:help lspconfig-setup`
    cmd = { "rust-analyzer" },
    root_dir = lspconfig.util.root_pattern("Cargo.toml", "rust-project.json"),
    settings = {
       ['rust-analyzer'] = {
         cargo = {
          loadOutDirsFromCheck = true
        },
        procMacro = {
          enable = true
        }
      },
    }
  }
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
on_event = 'BufEnter'
lua_source = '''
  local mason = require('mason')
  mason.setup({
    PATH = "prepend",
    log_level = vim.log.levels.INFO,
    pip = {
      upgrade_pip = false,
    },
    ui = {
      width = 0.6,
      height = 0.7,
      icons = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗"
      }
    }
})
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_event = 'BufEnter'
depends = ['nvim-lspconfig.nvim', 'mason.nvim']
lua_source= '''
  local mason_lspconfig = require('mason-lspconfig')
  mason_lspconfig.setup{}
'''
