[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufEnter'
lua_source = '''
  local nvim_lspconfig = require('lspconfig')
  vim.keymap.set('n', 'ge', vim.diagnostic.open_float)
  vim.keymap.set('n', 'g[', vim.diagnostic.goto_prev)
  vim.keymap.set('n', 'g]', vim.diagnostic.goto_next)
  vim.lsp.set_log_level("debug")
  nvim_lspconfig.rust_analyzer.setup {}
  vim.api.nvim_create_autocmd('LspAttach', {
    group = vim.api.nvim_create_augroup('UserLspConfig', {}),
    callback = function(ev)
      local opts = { buffer = ev.buf }
      vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
      vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
      vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
      vim.keymap.set('n', 'gk>', vim.lsp.buf.signature_help, opts)
      vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
      vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
      vim.keymap.set('n', '<space>wl', function()
        print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
      end, opts)
      vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
      vim.keymap.set({ 'n', 'v' }, '<space>ca', vim.lsp.buf.code_action, opts)
    end,
  })
  vim.cmd [[autocmd BufWritePre * lua vim.lsp.buf.format()]]
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
on_event = 'BufEnter'
lua_source = '''
  local mason = require('mason')
  mason.setup({
    PATH = "prepend",
    log_level = vim.log.levels.INFO,
    pip = {
      upgrade_pip = false,
    },
    ui = {
      width = 0.6,
      height = 0.7,
      icons = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗"
      }
    }
})
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_event = 'BufEnter'
depends = ['nvim-lspconfig.nvim', 'mason.nvim']
lua_source= '''
  local mason_lspconfig = require('mason-lspconfig')
'''
