[[plugins]]
repo = 'echasnovski/mini.nvim'
on_event = 'BufRead'
hook_add = '''
lua << EOF
require('mini.indentscope').setup()
EOF
'''

# ファイルタイプに合わせて、いい感じにコメントアウトしてくれるプラグイン
[[plugins]]
repo = 'echasnovski/mini.comment'
on_event = 'BufRead'
## キーマッピング
# -- 通常モードとビジュアルモードの両方で、コメント (`gcip` - コメント内段落のようなもの) をトグルする。
# comment = 'gc',
# -- 通常モードで、コメント (`gcc` - 行コメント) をトグルする。
# comment_line = 'gcc',
# ビジュアルモードで、選択範囲をコメントアウトする。
# comment_visual = 'gc',

# インデントの範囲を表示してくれるプラグインです。
# インデント関係のテキストオブジェクトも提供


# 複数の引数を一発で分割・結合してくれるプラグイン
[[plugins]]
repo = 'echasnovski/mini.splitjoin'
