name: Setup Neovim


on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string


jobs:
  setup-neovim:
    name: Setup Neovim Environment
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-docker-image.outputs.image_name }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Neovim
      run: .bin/utils/setup_neovim.sh
