name: Setup Neovim


on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string


jobs:
  setup-neovim:
    name: Setup Neovim Environment
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_name }}
    steps:
    - name: Check environment
      run: |
        echo "Current user: $(whoami)"
        echo "Current directory: $(pwd)"
        echo "Home directory: $HOME"
        echo "PATH: $PATH"
        echo "Installed packages:"
        if command -v pacman &> /dev/null; then
          pacman -Q | grep nvim
          echo "Arch"
        elif command -v dpkg &> /dev/null; then
          dpkg -l | grep nvim
          echo "Ubuntu"
        fi
        echo "Neovim installation:"
        which nvim || echo "nvim not found"
        nvim --version || echo "nvim --version failed"
    - uses: actions/checkout@v4
    - name: Setup Neovim
      run: .bin/utils/setup_neovim.sh
