name: Setup Environment

on:

  workflow_call:
    inputs:
      script_path:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:

        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run setup script

        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ghcr.io/${{ github.repository }}/dotfiles-env:${{ github.sha }} \

            ${{ inputs.script_path }}
