name: Setup Neovim


on:
  workflow_call:

jobs:
  common-setup:
    uses: ./.github/workflows/setup-common.yml

  setup-neovim:
    needs: common-setup
    name: Setup Neovim Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{fromJson(needs.common-setup.outputs.matrix)}}
    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Neovim
      run: .bin/utils/setup_neovim.sh
