name: Setup Base

on:
  workflow_call:



jobs:
  setup-base:
    name: Setup Base Environment
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/dotfiles-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - name: Test Setup base Script
      run: .bin/utils/setup_base.sh
