name: Setup Rust

on:
  workflow_call:

jobs:
  setup-rust:
    name: Setup Rust Environment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ['ubuntu:latest', 'archlinux:base-devel']
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

    # セットアップスクリプトの実行
    # TODO: stable, nightly, betaで何れか通ったら次のステップに進むようにしたい
    # これは、gituiがエラーを出すため
    # gitui0.26.2のnightlyがエラーを出すため、一旦continue-on-errorを設定
    - name: Test Setup Rust Script
      run: .bin/utils/setup_rust_tools.sh
      continue-on-error: true
