name: Setup Fish Shell


on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  common-setup:
    uses: ./.github/workflows/setup-common.yml

  setup-neovim:
    needs: common-setup
    name: Setup Fish Shell
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-docker-image.outputs.image_name }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Fish shell
      run: .bin/utils/setup_fish.sh
