name: Setup Neovim


on:
  workflow_call:


jobs:
  setup-neovim:
    name: Setup Neovim Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Log in to GitHub Container Registry

      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Neovim
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          ghcr.io/${{ github.repository }}/dotfiles-env:${{ github.sha }} \
          .bin/utils/setup_neovim.sh
