name: Setup Terminal


on:
  workflow_call:

jobs:
  setup-terminal:
    name: Setup Terminal Environment
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/dotfiles-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup symlinks
      run: .bin/utils/setup_symlinks.sh

    - name: Setup directories
      run: .bin/utils/setup_directories.sh

    - name: Setup terminal
      run: .bin/utils/setup_tmux.sh

    # セットアップスクリプトの実行
    # TODO: stable, nightly, betaで何れか通ったら次のステップに進むようにしたい
    # これは、gituiがエラーを出すため
    # gitui0.26.2のnightlyがエラーを出すため、一旦continue-on-errorを設定
    - name: Setup Git config
      run: .bin/utils/setup_git.sh
      continue-on-error: true
